apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-split-monorepo
spec:
  type: url
  owner: dhrumit
  lifecycle: experimental
  targets:
    - ./test-dir/dir-1/backstage.yaml
    - ./test-dir/dir-2/backstage.yaml
